config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  resources :collections
  resources :users #, only: [:new, :create, :index, :show, :edit]
  get 'users/:id/notes', to: "notes#user_notes"
  get 'users/:id/collections', to: "collections#user_collections"

  get 'collections/:id_collection/notes', to: "notes#collection_notes"
  get 'users/:id_user/collections/:id_collection/notes', to: "notes#collection_notes"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  
  resources :notes #plural 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :nullify
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  add_flash_types :danger, :info, :warning, :success, :notice

  before_action :set_collection, only: %i[ show edit update destroy ]
  before_action :admin_permission, only: [:user_collections]

  # GET /collections or /collections.json
  def index
    @collections = Collection.where(user_id: current_user.id)
  end

  #admin_management
  def user_collections
    @collections = Collection.where(user_id: params[:id])
  end

  # GET /collections/1 or /collections/1.json
  def show
    @collection = Collection.find(params[:id])
    if @collection.user_id == current_user.id || is_admin?

    else 
      flash[:danger] = "Unauthorized" 
      redirect_to collections_path
    end

  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
    if @collection.user_id == current_user.id || is_admin?

    else 
      flash[:danger] = "Unauthorized" 
      redirect_to collections_path
    end
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)
    @collection.user_id = current_user.id

    if @collection.save
      flash[:success] =  "Collection was successfully created."
      redirect_to @collection
    end
    
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
      if @collection.update(collection_params)
        flash[:info] =  "Collection was successfully updated."
        redirect_to collections_path
      end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy
    flash[:danger] = "The collection was successfully destroyed." 
    redirect_to collections_url 

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:name, :user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_with(model: collection) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
  <% end %>
 
  <div class ="grid container align-items-center">
    <div class="text-center p-3">
      <grid item xs={6}>
        <%= form.label :Name %>
      </grid>
      <grid item xs={6}>
        <%= form.text_field :name %>
      </grid><br>
      <grid item xs={6}>
        <%= form.submit(class:'btn btn-dark')%>
      </grid><br>
   </div>
  </div>
<% end %>

app/views/collections/_listCollections.html.erb
<div class="container">
  <div class="row align-items-center">
    <h1>Collections</h1>
    <p class = "text-center" id="notice"><%= notice %></p>
  </div>
</div>
<div class="text-center">
<div class ="btn-group gap-2 center mx-3 " >
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      
    </tr>

  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= link_to collection.name, "collections/#{collection.id}/notes" %></td>
        <td>
        <td><%= link_to 'Edit', edit_collection_path(collection), class:"btn btn-dark"; %></td> 
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-dark"; %></td>
        </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

app/views/collections/edit.html.erb
<h1>Edit Collection</h1>
<div class="text-center">
  <div class="row align-items-center">
  <%= render 'form', collection: @collection %>
      
  </div>
</div>




        
     

app/views/collections/index.html.erb
<div class="text-center p-3">

<%= render "listCollections", collection: @collections %>

</div>
<div class="text-center">
    <div class ="btn-group gap-2 col-md-2  mx-3 " >
      

        <%= link_to 'New Collection', new_collection_path , class:"btn btn-dark" %>
    </div>
</div>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>


<div class="text-center p-3">
<div class ="btn-group col-md-1  mx-3" >
<%= link_to 'Back', collections_path , class:"btn btn-dark"; %>
</div>
</div>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
    <div class ="btn-group gap-2 col-md-2  mx-3 " >
<p>
  <strong>Name:</strong>
  <%= @collection.name%>
</p>

</div>
</div>
<div class="text-center">
    <div class ="btn-group gap-2 col-md-2  mx-3 " >
<%= link_to 'Edit', edit_collection_path(@collection) , class:"btn btn-dark";%> |
<%= link_to 'Back', collections_path, class:"btn btn-dark"; %>
</div>
</div>

app/views/collections/user_collections.html.erb
<%= render "listCollections", collection: @collections %>