config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  resources :collections
  resources :users #, only: [:new, :create, :index, :show, :edit]
  get 'users/:id/notes', to: "notes#user_notes"
  get 'users/:id/collections', to: "collections#user_collections"

  get 'collections/:id_collection/notes', to: "notes#collection_notes"
  get 'users/:id_user/collections/:id_collection/notes', to: "notes#collection_notes"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  
  resources :notes #plural 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
    validates :body, presence: true
    belongs_to :user
    has_many :collections
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  add_flash_types :danger, :info, :warning, :success, :notice

  before_action :admin_permission, only: [:user_notes,:collection_notes]

  def index
      @notes = Note.where(user_id: current_user.id)
  end

  #admin_management
  def user_notes
    
    if is_admin?
      @notes = Note.where(user_id: params[:id])
    else
      flash[:danger] = "Unauthorized" 
    end 
  end

  def collection_notes
    @notes = Note.where(collection_id: params[:id_collection])
  end

  def show
    @note = Note.find(params[:id])

    if @note.collection_id == nil

    else  
      @collection = Collection.find(@note.collection_id)
    end

    if @note.user_id == current_user.id || is_admin?

    else 
      flash[:danger] = "Unauthorized" 
      redirect_to notes_path
    end
  end


  def new
    @note = Note.new
    @collections = current_user.collections
    
  end

  def create
    @note = Note.new(note_params)

    @note.user_id = current_user.id

    if @note.save
      flash[:success] =  "Note was successfully created."
      redirect_to @note
    else
      flash[:danger] = "There was a problem, try again." 
      render :new
    end
  end

  def edit
    @note = Note.find(params[:id])
    @collections = current_user.collections
    if @note.user_id == current_user.id || is_admin?

    else
      flash[:danger] = "Unauthorized" 
      redirect_to notes_path
    end
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(note_params)
      flash[:info] =  "Note was successfully updated."
      redirect_to @note
    else
      flash[:danger] = "There was a problem, try again." 
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    flash[:danger] = "The note was successfully destroyed." 
    redirect_to notes_path
  end

  private
    def note_params
      params.require(:note).permit(:title, :body, :image, :user_id, :collection_id)
    end
  
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with model: note do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% note.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% note.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
        <%= form.label :image %><br>
        <%= form.text_field :image %>
    </div>

      <%= form.select :collection_id, @collections.map { |c| [c.name, c.id] } << ['None', nil] %>
    
    <div>

      <%= form.submit class: "btn btn-dark mt-2" %>
    </div>
  <% end %>
  

app/views/notes/_listNotes.html.erb
<h1>Notes</h1>
<dt class = "text-center"> In this page you can create your own notes! Give it a try! </dt>
<div class="text-center p-3">
  <div class ="btn-group gap-2 col-md-2  mx-3" >
<ul>
  <% @notes.each do |note| %>
    <li>
        <span>
        <%= link_to note.title, note %>
        </span>

    </li>
  <% end %>
</ul>
</div>
</div>

app/views/notes/collection_notes.html.erb
<%= render "listNotes", note: @notes %>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<div class="text-center">
<div class ="btn-group gap-2 col-md-2  mx-3 " >
<%= render "form", note: @note %>
</div>
</div>

app/views/notes/index.html.erb
<%= render "listNotes", note: @notes %>


<div class="text-center">
<div class ="btn-group gap-2 col-md-2  mx-3 " >
<%=link_to "New Note", new_note_path, class:"btn btn-dark";%>
</div>
</div>

app/views/notes/new.html.erb
<h1>New Note</h1>
<div class="text-center">
<div class ="btn-group gap-2 col-md-2  mx-3 " >
<%= render "form", note: @note %>
</div>
</div>

app/views/notes/show.html.erb
<div class="text-center">
  <h1> <%= @note.title %> </h1>
      <p style="color:white">
        Note created by: <%= @note.user.email %>
      </p>
      

<div class="container p-3 my-3 bg-dark text-white"
<p> <%= @note.body %> </p>
  <br>
<img class="img-responsive" src="<%= @note.image%>" width="460" height="345">

</div>
<p style="color:white">
Collection: 
<% if @collection %>
  <%= @collection.name %>
<%else%>
  None
<%end%>
</p>

</div>
<div class="text-center">
  <div class ="btn-group gap-2 col-md-2  mx-3" >
<ul>
  <%= link_to"Edit", edit_note_path(@note), class: "btn btn-dark" %></li>
  <%= link_to "Delete", note_path(@note), class:"btn btn-dark",
                  method: :delete,
                  data: { confirm: "Do you want to delete this note?" } %></li>
</ul>
</div>
</div>

app/views/notes/user_notes.html.erb
<%= render "listNotes", note: @notes %>