config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  resources :collections
  resources :users #, only: [:new, :create, :index, :show, :edit]
  get 'users/:id/notes', to: "notes#user_notes"
  get 'users/:id/collections', to: "collections#user_collections"

  get 'collections/:id_collection/notes', to: "notes#collection_notes"
  get 'users/:id_user/collections/:id_collection/notes', to: "notes#collection_notes"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  
  resources :notes #plural 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<header>
    <div class="h1_container">
    <h2>Welcome to our spidey-notes app!</h2>
       <%= image_tag "spider.jpeg", class: "image1"%>
        <nav>
            <ul>
            <li> <%= link_to "Home" ,root_path, class: "boton"%></li>
            <li> <%= link_to "Collections",root_path, class: "boton"%></li>
            <li> <%= link_to "Friends",new_note_path, class: "boton" %></li>
            <% if user_signed_in? %>
                <% if current_user.is_admin? %>
                    <li> <%= link_to "Users" ,root_path, class: "boton"%> </li>
                <%end%>
            <%end%>   
            <p style= "color:#364A73"> 
            _
            </p>        
            <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
                <li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li> |
                <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
            <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="/welcome">Spidey-Notes App!</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav" >
      <ul class="navbar-nav">

        <% if logged_in? %>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/notes">Notes</a>
        </li>
          <% if is_admin? %>
            <li> <%= link_to "Users" , users_path, :class => "nav-link"%> </li>
          
          <%end%>
            <li> <%= link_to "Collections" , collections_path, :class => "nav-link"%> </li>
        <%end%>   
        </ul>
        </div>
     
        <% if logged_in? %>
                Logged in as : <strong><%= current_user.email %></strong>.
                <%= link_to "Logout", "/logout", :class => 'nav-link'  %>
                <%= link_to "Edit Profile", edit_user_path(current_user), :class => 'nav-link'  %>
        <% else %>
                <a class="nav-link" href="/login", method:get, role="button" aria-pressed="true">Login</a>
                <a class="nav-link" href="/users/new", method:get, role="button" aria-pressed="true">Sign Up</a>
        <% end %>
        </div>  
</nav>
    <div id='main' class='container'>
      <div class='row'>

        <% flash.each do |name, msg| %>
          <div class='alert alert-<%= name %>'>
            <%= msg %>
          </div>
        <% end %>
        
        <%= yield %>
        
      </div> 
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>